dist: xenial

services:
  - docker

before_install:
  - git fetch origin +refs/heads/$TRAVIS_BRANCH

script:
- MANUAL_SRC_PATH=$PWD OSS_FUZZ_PROJECT_NAME='cifuzz-example' REPO_NAME='cifuzz-example' COMMIT_SHA=$TRAVIS_PULL_REQUEST_SHA ./travis-cifuzz.bash
